name: ✨ Feature Request
description: Suggest a new feature or enhancement for the 3D Inventory API
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees:
  - karol-preiskorn

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm always frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of what you want to happen
      placeholder: I propose adding...
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New API Endpoint
        - Existing Endpoint Enhancement
        - New Service/Business Logic
        - Performance Improvement
        - Developer Experience (DX)
        - Infrastructure/DevOps
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (important for workflow)
        - Medium (nice to have)
        - Low (future consideration)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've considered using... / An alternative approach could be...
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: API Example (if applicable)
      description: If proposing an API change, provide example request/response
      placeholder: |
        POST /api/new-endpoint
        {
          "example": "request"
        }
      render: json
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. As a user, I need...
        2. This would enable...
    validations:
      required: false

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Notes
      description: Any thoughts on how this could be implemented? (optional)
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: Related documentation, similar features in other APIs, etc.
    validations:
      required: false

  - type: checkboxes
    id: pre-submission
    attributes:
      label: Pre-submission Checklist
      description: Please verify you've completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have clearly described the problem and proposed solution
          required: true
        - label: This feature aligns with the project goals
          required: false
        - label: I am willing to help implement this feature
          required: false
