name: 🔒 Security Vulnerability
description: Report a security vulnerability (please use privately if critical)
title: "[Security]: "
labels: ["security", "needs-triage"]
assignees:
  - karol-preiskorn

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a critical security vulnerability that could be actively exploited,
        please report it privately via GitHub Security Advisories instead of creating a public issue.

        Go to: https://github.com/karol-preiskorn/3d-inventory-mongo-api/security/advisories/new

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Critical (remote code execution, data breach)
        - High (authentication bypass, privilege escalation)
        - Medium (information disclosure, DoS)
        - Low (security hardening, best practices)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: The API endpoint X allows...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Vulnerability Category
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Injection (SQL, NoSQL, Command)
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Direct Object Reference (IDOR)
        - Security Misconfiguration
        - Sensitive Data Exposure
        - Dependency Vulnerability
        - Denial of Service (DoS)
        - Other
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What is the potential impact of this vulnerability?
      placeholder: An attacker could...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced?
      placeholder: |
        1. Send malicious request to...
        2. Observe that...
    validations:
      required: true

  - type: textarea
    id: affected
    attributes:
      label: Affected Components
      description: Which parts of the system are affected?
      placeholder: |
        - API endpoint: /api/...
        - Service: UserService
        - Middleware: auth.ts
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have suggestions for fixing this vulnerability?
      placeholder: This could be fixed by...
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to CVEs, OWASP guidelines, or related security advisories
      placeholder: |
        - CVE-2023-XXXX
        - OWASP: https://owasp.org/...
    validations:
      required: false

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm responsible disclosure practices
      options:
        - label: I am reporting this vulnerability responsibly and will not disclose it publicly until it is fixed
          required: true
        - label: I have not exploited this vulnerability beyond what was necessary to demonstrate it
          required: true
        - label: I understand this issue may be kept private until a fix is available
          required: true
