# TODO: fix device POST with seting from body
# TODO: fix device GET


### get devices

GET http://localhost:8080/devices HTTP/1.1
content-type: application/json

{
    "device_id": "sample3",
    "device_name": "device-name-a1",
    "device_category": "Server",
    "device_type": "Racks"
}


### post device

POST http://localhost:8080/devices HTTP/1.1
content-type: application/json

{
    "device_id": "sample45",
    "device_name": "device-name-a1",
    "device_category": "Server",
    "device_type": "Racks"
}

### post device

PUT http://localhost:8080/devices HTTP/1.1
content-type: application/json

{
    "device_id": "sample3",
    "device_name": "device-name-a1",
    "device_category": "Server",
    "device_type": "Racks"
}


### get request selected devices

GET http://localhost:8080/devices HTTP/1.1
content-type: application/json

{

}

### get request selected context

GET http://localhost:8080/devices HTTP/1.1
content-type: application/json

{
    "device_name": "tall_turquoise_sheep"
}


### get logs

GET http://localhost:8080/logs HTTP/1.1
content-type: application/json

### get request selected context

POST http://localhost:8080/logs HTTP/1.1
content-type: application/json

{
 "objectId": "65b67f8bf42bf190aca7029d",
 "operation": "Update",
 "component": "Devices",
 "message": "{\"_id\":\"65b67f8bf42bf190aca7029d\",\"name\":\"Gloves pink-cow\",\"modelId\":\"65b67f8bf42bf190aca7029b\",\"position\":{\"x\":43,\"y\":86,\"h\":\"0\"}}"
}

### get logs

GET http://localhost:8080/logs/65f15b8b56931f757dfb1936 HTTP/1.1
content-type: application/json


###

PUT http://localhost:8080/logs HTTP/1.1
content-type: application/json

{
    "device_name": "tall_turquoise_sheep"
}

### get logs for components

GET http://localhost:8080/logs/component/devices HTTP/1.1
content-type: application/json
