# @Url = https://172.17.0.2:3001
@Url = https://172.17.0.2:3001
@UrlLocal = https://localhost:3001


### GH
GET {{Url}}/github/issues
content-type: application/json

### ATTRIBUTES DICTIONARY
GET {{Url}}/attributesDictionary
content-type: application/json

### ATTRIBUTES DICTIONARY
GET {{Url}}/attributesDictionary/674209f981bfc47a07217dfd
content-type: application/json

### ATTRIBUTES DICTIONARY PUT
PUT {{Url}}/attributesDictionary/674209f981bfc47a07217dfd
content-type: application/json

{
  "component": "connection",
  "type": "Object",
  "name": "Hard drive Blue Chair",
  "units": "Type"
}

### Attributes PUT
PUT {{Url}}/attributes/65c2bbf4e6e6d4ea3d39875d
content-type: application/json

{
  "_id": "65c2bbf4e6e6d4ea3d39875d",
  "attributeDictionaryId": "674209f981bfc47a07217dfd",
  "connectionId": "",
  "deviceId": "66c217c7165fc0a329627089",
  "modelId": "",
  "value": "Handcrafted"
}

### Attributes GET
GET {{Url}}/attributes
content-type: application/json

### Attributes GET
GET {{Url}}/attributes/65c2bbf4e6e6d4ea3d39875d
content-type: application/json


### connections
GET {{Url}}/connections
content-type: application/json

### connection update
PUT {{Url}}/connections/65cbd0f7fb3ea819dbcdbfb4
content-type: application/json

{
 "name": "turquoise Device",
 "deviceIdTo": "65b67f8cf42bf190aca702a9",
 "deviceIdFrom": "65b67f8df42bf190aca702ad"
}

### get all devices
GET {{Url}}/devices
content-type: application/json

### get request selected devices
GET {{Url}}/devices
content-type: application/json

{
    "device_id": "sample3",
    "device_name": "device-name-a1",
    "device_category": "Server",
    "device_type": "Racks"
}

### post device
POST {{Url}}/devices
content-type: application/json

{
  "name": "Device 5",
  "modelId": "666f1f97468aefc2cafefa18",
  "position": {
    "x": 11,
    "y": 3,
    "h": 3
  },
  "attributes": [
    {
      "key": "color",
      "value": "red"
    },
        {
      "key": "power",
      "value": "100W"
    }
  ]
}

### put device
PUT {{Url}}/devices
content-type: application/json

{
    "device_id": "sample3",
}

### get request selected context
GET {{Url}}/devices
content-type: application/json

{
    "device_name": "tall_turquoise_sheep"
}


### update device
PUT {{Url}}/devices/66f194a97daf5ff819e1492d
content-type: application/json

{
    "name": "Gloves Device-3",
    "modelId": "683185eb26844932fb3a8d4c",
    "position": {
        "x": 22,
        "y": 10,
        "h": 0
    }
}

### get device by id
GET {{Url}}/devices/65b67f8bf42bf190aca7029d
content-type: application/json

### get all model
GET {{Url}}/models
content-type: application/json

### get model
GET {{Url}}/models/65b67f8bf42bf190aca7029b
content-type: application/json

### update model
PUT {{Url}}/models/65b67f8bf42bf190aca7029b
content-type: application/json

{ "id": "65b67f8bf42bf190aca7029b", "name": "Mode 1", "dimension": { "width": "0", "height": "0", "depth": "0" }, "texture": { "front": "/assets/r710-2.5-nobezel__29341.png", "back": "/assets/r710-2.5-nobezel__29341.png", "side": "/assets/r710-2.5-nobezel__29341.png", "top": "/assets/r710-2.5-nobezel__29341.png", "bottom": "/assets/r710-2.5-nobezel__29341.png" }, "type": "Power", "category": "Site" }

### create model
POST {{Url}}/models
content-type: application/json

{ "name": "Mode 4", "dimension": { "width": "5", "height": "8", "depth": "1" }, "texture": { "front": "/assets/r710-2.5-nobezel__29341.png", "back": "/assets/r710-2.5-nobezel__29341.png", "side": "/assets/r710-2.5-nobezel__29341.png", "top": "/assets/r710-2.5-nobezel__29341.png", "bottom": "/assets/r710-2.5-nobezel__29341.png" }, "type": "Power", "category": "Site" }

### get logs
GET {{Url}}/logs
content-type: application/json

### get request selected context (logs)
POST {{Url}}/logs
content-type: application/json

{
 "objectId": "65b67f8bf42bf190aca7029d",
 "operation": "Update",
 "component": "Devices",
 "message": "{\"_id\":\"65b67f8bf42bf190aca7029d\",\"name\":\"Gloves pink-cow\",\"modelId\":\"65b67f8bf42bf190aca7029b\",\"position\":{\"x\":43,\"y\":86,\"h\":\"0\"}}"
}

### get log by id
GET {{Url}}/logs/65f15b8b56931f757dfb1936
content-type: application/json

### update log
PUT {{Url}}/logs
content-type: application/json

{
    "device_name": "tall_turquoise_sheep"
}

### get logs for components
GET {{Url}}/logs/component/devices
content-type: application/json

### Logs components
GET {{UrlLocal}}/logs/component/attributes
content-type: application/json

### connections logs
GET {{Url}}/logs/component/connections
content-type: application/json

### get github issues
GET https://api.github.com/repos/karol-preiskorn/3d-inventory-angular-ui/issues
content-type: application/json
X-GitHub-Api-Version: 2022-11-28
