name: 'Configure GitHub Pages'
on:
  push:
    branches:
      - main

jobs:
  configure-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run your action logic
        id: my_step
        run: |
          echo "Running with ${{ inputs.static_site_generator }}"
          echo "base_url=https://example.com" >> $GITHUB_OUTPUT
