name: Docker Image CI
description: Build a Docker image for the repository

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      shell: bash
