jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type checking
        run: npm run type-check

      - env:
          CI: true
        name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

name: Node.js CI
# Add description for better documentation
# description: 'Continuous Integration workflow for Node.js project with TypeScript'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
